non_free_repos:
  - deb http://deb.debian.org/debian trixie main contrib non-free
  - deb-src http://deb.debian.org/debian trixie main contrib non-free
  - deb http://deb.debian.org/debian-security/ trixie-security main contrib non-free
  - deb-src http://deb.debian.org/debian-security/ trixie-security main contrib non-free
  - deb http://deb.debian.org/debian trixie-updates main contrib non-free
  - deb-src http://deb.debian.org/debian trixie-updates main contrib non-free
valheim_ports:
  - "2456"
  - "2457"
server_name: "Valheim"
world_name: "server"
server_password: "xxxxx"
